import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from '../../../../libs/shared/shadcn/src/components/ui/sonner';
import './global.css';
import { LayoutHeader } from './homepage/_components/LayoutHeader';

export const metadata = {
  title: 'Welcome to ReferU',
  description: 'Generated by create-nx-workspace',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY!}>
    <html lang="en">
      <body className="min-h-screen overflow-x-hidden">
        <main className="w-full max-w-\[430px]\ min-h-\[932px]\ bg-white">
          <LayoutHeader/>
          {children}
          <Toaster position="top-center" />
        </main>
      </body>
    </html>
    </ClerkProvider>
  );
}
