import { ClerkProvider } from '@clerk/nextjs';
import type { Viewport } from 'next';
import { Header } from './_components/Header';
import './global.css';

export const metadata = {
  title: 'Welcome to referu-employee-fe',
  description: 'Generated by create-nx-workspace',
};

export const viewport: Viewport = {
  // themeColor: 'black',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen overflow-x-hidden">
          <main className="w-full max-w-\[430px]\ min-h-\[932px]\ bg-[#005295]/5">
            <Header />
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
