import { AdminLayout } from '../_components/main/AdminLayout';

export const metadata = {
  title: 'Welcome to management4everyone',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <AdminLayout>
        <body>{children}</body>
      </AdminLayout>
    </html>
  );
}
