export const hrPostedJobs = [
  {
    _id: 'job001',
    jobTitle: 'Веб хөгжүүлэгч',
    jobDepartment: 'Инженеринг',
    jobType: 'Бүтэн цагийн',
    jobLevel: 'Дунд шатны ажилтан',
    salaryMin: 2500000,
    salaryMax: 3200000,
    keyDuties: ['Веб аппликейшн хөгжүүлэх', 'Unit тест бичих', 'Багтай хамтран ажиллах'],
    requirements: ['Компьютерийн шинжлэх ухааны бакалавр', '2+ жил вэб хөгжүүлэлт', 'JavaScript/TypeScript мэддэг'],
    additionalNotes: 'Алсын зайнаас ажиллах боломжтой',
    requiredSkills: ['JavaScript', 'React', 'Node.js'],
    benefits: ['Эрүүл мэндийн даатгал', 'Амралтын цаг', 'Уян хатан цаг'],
    contactInfo: 'hr@company.mn',
    location: 'Баянгол дүүрэг, 3-р хороо, Sky Tower, 5 давхар оффис',
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
  {
    _id: 'job002',
    jobTitle: 'Frontend хөгжүүлэгч',
    jobDepartment: 'Инженеринг',
    jobType: 'Бүтэн цагийн',
    jobLevel: 'Эхний шатны ажилтан',
    salaryMin: 2500000,
    salaryMax: 3000000,
    keyDuties: ['UI компонент үүсгэх', 'Responsive дизайн хийх', 'Performance сайжруулах'],
    requirements: ['HTML, CSS, JS мэддэг', 'React эсвэл Vue туршлагатай'],
    requiredSkills: ['React', 'TailwindCSS', 'Git'],
    benefits: ['Гимнастикийн клубын эрх', 'Эрүүл мэндийн даатгал'],
    additionalNotes: 'Алсын зайнаас ажиллах боломжтой',
    contactInfo: 'jobs@company.mn',
    location: 'Сүхбаатар дүүрэг, 6-р хороо, Шангри-Ла бизнес төв, 3 давхар оффис',
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
  {
    _id: 'job003',
    jobTitle: 'Backend хөгжүүлэгч',
    jobDepartment: 'Инженеринг',
    jobType: 'Гэрээт',
    jobLevel: 'Дунд шатны ажилтан',
    salaryMin: 2600000,
    salaryMax: 3500000,
    keyDuties: ['API зохион байгуулах', 'Database удирдах', 'Server-side код оновчлох'],
    requirements: ['Node.js эсвэл Python мэддэг', 'SQL/NoSQL database мэдлэгтэй'],
    requiredSkills: ['Node.js', 'MongoDB', 'REST APIs'],
    benefits: ['Remote ажиллах боломж', 'Уян хатан цаг'],
    additionalNotes: 'Тодорхой хугацааны гэрээтэй',
    contactInfo: 'backend@company.mn',
    location: 'Хан-Уул дүүрэг, 11-р хороо, Blue Sky Tower, 4 давхар оффис',
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
  {
    _id: 'job004',
    jobTitle: 'UI/UX дизайнер',
    jobDepartment: 'Дизайн',
    jobType: 'Бүтэн цагийн',
    jobLevel: 'Ахлах ажилтан',
    salaryMin: 2800000,
    salaryMax: 3500000,
    keyDuties: ['User flow үүсгэх', 'Wireframe дизайн хийх', 'Frontend багтай хамтран ажиллах'],
    requirements: ['Portfolio шаардлагатай', '3+ жил UI/UX туршлага'],
    requiredSkills: ['Figma', 'Adobe XD', 'User research'],
    benefits: ['Эрүүл мэндийн даатгал', 'Амралтын цаг'],
    additionalNotes: 'Алсын зайнаас ажиллах боломжтой',
    contactInfo: 'design@company.mn',
    location: 'Чингэлтэй дүүрэг, 4-р хороо, Crown Tower, 6 давхар оффис',
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
  {
    _id: 'job005',
    jobTitle: 'Бүтээгдэхүүний менежер',
    jobDepartment: 'Продукт',
    jobType: 'Бүтэн цагийн',
    jobLevel: 'Менежер',
    salaryMin: 3000000,
    salaryMax: 3500000,
    keyDuties: ['Product roadmap тодорхойлох', 'Багуудыг зохицуулах', 'Release удирдах'],
    requirements: ['5+ жил product management', 'Сайн харилцааны ур чадвар'],
    requiredSkills: ['Jira', 'Notion', 'Roadmapping'],
    benefits: ['Эрүүл мэндийн даатгал', 'Уян хатан цаг'],
    additionalNotes: 'Алсын зайнаас ажиллах боломжтой',
    contactInfo: 'pm@company.mn',
    location: 'Баянзүрх дүүрэг, 15-р хороо, Grand Tower, 5 давхар оффис',
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
  {
    _id: 'job006',
    jobTitle: 'Маркетинг мэргэжилтэн',
    jobDepartment: 'Маркетинг',
    jobType: 'Бүтэн цагийн',
    jobLevel: 'Эхний шатны ажилтан',
    salaryMin: 2500000,
    salaryMax: 3000000,
    keyDuties: ['Social media менежмент', 'Content creation', 'SEO оновчлол'],
    requirements: ['Digital marketing туршлага', 'Analytics tool мэдлэгтэй'],
    requiredSkills: ['SEO', 'Google Analytics', 'Canva'],
    benefits: ['Уян хатан цаг', 'Эрүүл мэндийн даатгал'],
    additionalNotes: 'Алсын зайнаас ажиллах боломжтой',
    contactInfo: 'marketing@company.mn',
    location: 'Сонгинохайрхан дүүрэг, 7-р хороо, Sky City, 2 давхар оффис',
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
  {
    _id: 'job007',
    jobTitle: 'Борлуулалтын ажилтан',
    jobDepartment: 'Борлуулалт',
    jobType: 'Бүтэн цагийн',
    jobLevel: 'Дунд шатны ажилтан',
    salaryMin: 2600000,
    salaryMax: 3200000,
    keyDuties: ['Клиент олох', 'Leads үүсгэх', 'Sales тайлан гаргах'],
    requirements: ['2+ жил sales туршлага', 'Сайн харилцааны ур чадвар'],
    requiredSkills: ['CRM', 'Negotiation', 'Presentation'],
    benefits: ['Эрүүл мэндийн даатгал', 'Комиссын бонус'],
    additionalNotes: 'Алсын зайнаас ажиллах боломжтой',
    contactInfo: 'sales@company.mn',
    location: 'Сүхбаатар дүүрэг, 2-р хороо, Central Tower, 3 давхар оффис',
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
  {
    _id: 'job008',
    jobTitle: 'HR менежер',
    jobDepartment: 'Хүний нөөц',
    jobType: 'Бүтэн цагийн',
    jobLevel: 'Менежер',
    salaryMin: 2800000,
    salaryMax: 3500000,
    keyDuties: ['Ажилд авах', 'Employee relations', 'Бодлого боловсруулах'],
    requirements: ['3+ жил HR туршлага', 'Хөдөлмөрийн хууль мэддэг'],
    requiredSkills: ['HRIS', 'Conflict resolution', 'Payroll'],
    benefits: ['Эрүүл мэндийн даатгал', 'Амралтын цаг'],
    additionalNotes: 'Алсын зайнаас ажиллах боломжтой',
    contactInfo: 'hr@company.mn',
    location: 'Хан-Уул дүүрэг, 12-р хороо, Green Tower, 4 давхар оффис',
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
  {
    _id: 'job009',
    jobTitle: 'Хэрэглэгчийн дэмжлэгийн ажилтан',
    jobDepartment: 'Support',
    jobType: 'Хагас цагийн',
    jobLevel: 'Эхний шатны ажилтан',
    salaryMin: 2500000,
    salaryMax: 2500000,
    keyDuties: ['Customer query хариулах', 'Troubleshooting заавар өгөх'],
    requirements: ['Сайн харилцааны ур чадвар', 'Customer service туршлага'],
    requiredSkills: ['CRM', 'Problem-solving'],
    benefits: ['Уян хатан цаг', 'Training provided'],
    additionalNotes: 'Алсын зайнаас ажиллах боломжтой',
    contactInfo: 'support@company.mn',
    location: 'Баянгол дүүрэг, 5-р хороо, Blue Tower, 2 давхар оффис',
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
];
