import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from '../../../../libs/shared/shadcn/src/components/ui/sonner';
import { Header } from './_components/Header';
import './global.css';

export const metadata = {
  title: 'Welcome to skill-hub',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
          <div className="max-w-\[1440px]\ m-auto">{children}</div>
          <Toaster position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  );
}
