import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: 'Welcome to management4everyone',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
