import {AdminLayout} from "@/components/main"

export const metadata = {
  title: 'Welcome to management4everyone',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <AdminLayout></AdminLayout>
      <body>{children}</body>
    </html>
  );
}
